---
apiVersion: v1
kind: Secret
metadata:
  name: s4t-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  username: admin
  password: admin
  domain: Default
---
apiVersion: s4t.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: s4t-provider-domain
spec:
  credentials:
    source: Secret
    secretRef:
      name: s4t-credentials
      namespace: crossplane-system
      key: credentials

